version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - "3000:3000"
    volumes:
      - /c/workspace/com.student/grafana/grafana-data:/var/lib/grafana/grafana-datase
      - /c/workspace/com.student/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini

